version: '3.4'

services:
  demoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - MONGO_URI=mongodb://mongoPlay:mongoPlay@mongo/MongoPlay
      - RABBIT_URI=amqp://guest:guest@rabbit:5672
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - mongo
      - rabbit
      - eventstore
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin   
    ports:
     - 27017:27017  
  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "8888:15672"  
      - "5672" 
  eventstore:
    container_name: esdb-docs-v5
    image: eventstore/eventstore
    command: --insecure
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:      
      EVENTSTORE_EXT_HTTP_PORT: 2113
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
      PROJECTION_THREADS: 8
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_DEV: 'true'
    #restart: always